### ISSUE TITLE
What tool should be doing the data movement?

### ISSUE THREAD

**Issue by bnlawrence** [cedadev/nlds#21]
The NLDS has four major internal data movement requirements:
 - ingestion from JASMIN POSIX disk
 - ingestion from JASMIN S3
 - migration to JASMIN tape cache S3
 - migration from JASMIN tape cache to JASMIN tape (S3 to xrootd?)

In each case the manifest of what needs to be moved is under the control of the NLDS. What is the best tool for this task and does it differ from the tools  we might use for offsite data migrations?

 - e.g. there is also the use-case where data is to be pulled from offsite (e.g. from ARCHER2), in which case we might expect the manifest to be provided to the NLDS, and the case where data wants to be pushed from offsite (e.g. from ARCHER2 or a laptop).
 -  The push case could be achieved by utilising transit cache.

The internal site movement might be "easily" parallelised by doing "file" movements in parallel, and  so tools like [minio](mini.io) or [rclone](https://rclone.org) might be suitable.

Offsite from ARCHER we might use faster tools (e.g. some version of GridFTP such as FT3 or indeed, Globus itself).
Offsite pushes from "small" servers may well work as well using S3 put which is likely more than enough to saturate the links typically in play for those sorts of servers.

Some of this is intimately related to the solutions we are likely to need for cfstore's cfmv ... which is  also likely to use either [minio](mini.io) or [rclone](https://rclone.org). It might be that the necessary thinking around managing migrations using these tools could be carried out in common.

**Comment by nmassey001** [comment]
For POSIX to Object Storage (and back): minio vs rclone

Minio
+ pure python, no dependancies outside standard python libs
- only perform S3 transfers

rclone
+ multiple cloud platforms supported, S3, Google, Azure, etc.
- potential complexity

**Comment by bnlawrence** [comment]
(Presumably we do this with some sort of plugin interface anyway? I am rather keen we do it using the manifest, transfer formalism discussed elsewhere.)
