### ISSUE TITLE
What do we do with links and empty directories?

### ISSUE THREAD

**Issue by nmassey001** [cedadev/nlds#32]
JDMA stored them in the database, as:

1. FILES
2. LINKS to files in the common path, whether defined relatively or absolutely
3. LINKS to files outside the common path, e.g. to system resources
4. DIRECTORIES

**Comment by bnlawrence** [comment]
Also want to avoid the situation where user A, who has no access to user B, puts a link to files owned by user B in their directory, and the NLDS (with root read priv) then follows the link and loads the target into the user A holdings allowing them to restore that data and get access nefariously.
