### ISSUE TITLE
URI for a file in NLDS

### ISSUE THREAD

**Issue by bnlawrence** [cedadev/nlds#42]
We will be needing AggregationFiles to point at fragments held in the NLDS, so we will need a URI for NLDS holdings. What would such a URI look like? And how would one generate a list of such URIs. 

Here is a concrete use case:

I have an aggregation file pointing at (say) 150 years of monthly data from a CANARI simulation. I want to move the last 140 years to the NLDS. I expect I can generate a list of the relevant fragments (manually or by the proposed CFA enhancements) and generate the relevant command to batch upload those files, but how when this is done, would I generate the list of new URIs to update in my AggregationFile?

**Comment by bnlawrence** [comment]
So, for a given quark, we want to be able to move it from tape (fast or slow) to S3 or POSIX ...

**Comment by nmassey001** [comment]
Two use cases:
1a. Retrieval to disk
1b. Retrieval to object store

2a. Ingest from disk to NLDS
2b. Ingest from object store to NLDS

**Comment by bnlawrence** [comment]
I think we would talk about 1b as staging, and that'd be really good, but it would require a method of obtaining the S3 URI from the system - but that'd be very desirable.

The full use case would cover (for an atomic dataset, using quark as the noun for a subset):
1. Identifying a quark in storage (cf-python's job), so it needs to be able to store NLDS URIs in CFA.
2. Being able to find the S3 URI for NDLS data held in object store (do we want to store those in CFA, or have a fast method to retrieve those?)
3. Being able to stage data (from tape) described by a "manifest of URIs" (i.e. a user/cf-python defined quark) to object store
4. Being able to retrieve data from NLDS by "manifest of URIs".

**Comment by nmassey001** [comment]
URIs / URLs for files can now be obtained by specifying the -U switch in the NLDS client:
in commit [55b4d0a](https://github.com/cedadev/nlds/commit/55b4d0a51e11d8d8b5d6f46a178db590aced8679)
