### ISSUE TITLE
Set up a test message passing system to test the flow of the PUT messages as outlined in the specification document.

### ISSUE THREAD

**Issue by nmassey001** [cedadev/nlds#5]

**Comment by jackleland** [comment]
Workflow (minus the actual indexer) now implemented, as of https://github.com/cedadev/nlds/pull/3/commits/7b66032d2a444b21d0c17ce37d36f1169d4ecddc

**Comment by jackleland** [comment]
Changes to workflow as respecified in the design document (edf702c87e5b3c53e7cb05505cf2874549f5bbd2 i.e. changing of routing keys) reflected in minor change to routing key constants in 9ccd04fcb22778934068f3628937818254c9ecf5. Other changes required in non-version-controlled config file.
