### ISSUE TITLE
NLDS system status page

### ISSUE THREAD

**Issue by nmassey001** [cedadev/nlds#64]
Provide a system status page for NLDS with up and down status for services.

**Comment by jackleland** [comment]
**Get set up and working with the NLDS**
- [ ] Read through the documentation to get a feel for what the NLDS does 
- [ ] Install NLDS on your local machine - instructions are on the github pages
	- [ ] Install `nlds` in edit mode from github 
	- [ ] Install `nlds-client` in edit mode from github
- [ ] Setup NLDS - get the config set up correctly 
	- [ ] Create venvs for use with each of `nlds` and `nlds-client`
	- [ ] Get server config set up correctly (ask me for an example)
	- [ ] Get client config set up (should be instructions on the github repo)
	- [ ] Log in to rabbit server and have a look around
- [ ] Run the NLDS system on your laptop 
	- [ ] Can use the `test_run/start_test_run.sh` and `test_run/stop_test_run.sh` scripts or can manually run each consumer and the server in different terminal windows -> up to you
	- [ ] Run your nlds-client for the first time (will need to log in)
	- [ ] Log in to the rabbit server to check your queues all exist in your vhost
- [ ] Run some test commands to check everything is working correctly
	- [ ] Run some test put workflows
		- [ ] This should be `nlds put path/to/file`
		- [ ] Try one with just a single file
		- [ ] Try one with a single file but giving it an explicit label (`nlds put --label=my-label path/to/file`)
		- [ ] Try one with a directory
		- [ ] Try one with list of files in a text file (`nlds putlist`)
		- [ ] Try one with a file or directory that doesn't exist
	- [ ] Use stat command
		- [ ] See how puts are progressing with a stat command (`nlds stat`)
		- [ ] Check on a particular job using a label 
	- [ ] Run a test get workflow
		- [ ] Delete one of the files you just put and then see if you can get it back using the `nlds get` command
	- [ ] Run a test of the database commands
		- [ ] Use `nlds list` to see your holdings
		- [ ] Use `nlds find` to see your files 
		- [ ] Use `nlds meta` to change some metadata (probably a label) on one of your holdings

**Development of the system status page:**
- [ ] Set up development environment
- [ ] Set up testing - install pytest
- [ ] Have a look at the router submodule in the nlds - what do you think it is doing?
- [ ] Browse to the liveness probe API endpoint (http://127.0.0.1:8000/probe/healthz) and see what is provided. We're going to make something similar!
- [ ] Try adding a command to the api server
	- [ ] Will need to make a new router
		- [ ] Use one of the existing ones as a template
	- [ ] Add an endpoint to FastAPI
		- [ ]  Add the new router into `main.py` to activate the new endpoint
	- [ ] Can just return a 'hello world' dictionary for now, but must be a part of a 'response' object, like in the other routers
	- [ ] Can be quite similar to the database commands (stat etc.)
	- [ ] Browse to the API endpoint you just created and see what is produced
- [ ] Get your router to send an RPC message to the monitoring consumer and wait for a response
- [ ] Optional: Add another RPC endpoint into the monitoring consumer to return just a simple status
- [ ] Return the status of the monitoring consumer in the response dict
- [ ] Browse to your API endpoint and see what is produced
- [ ] Add similar endpoints to the other consumers!
	- [ ] This will need fleshing out, will cross that bridge when we get there

Of course, please ask if you have any questions!

**Comment by jackleland** [comment]
Merged into `development` and now running as a [preview on staging](https://nlds-system-status.130.246.130.221.nip.io/). Closing as now complete.
