### ISSUE TITLE
Files being retried can still be attempted to be `GET`

### ISSUE THREAD

**Issue by jackleland** [cedadev/nlds#74]
Files that fail at the transfer step still appear in the catalog until they have failed for the final time, during which time users can still attempt to get them - which will obviously fail. The problem is this all takes a while with the long retry times (order of days when we get to the third retry) which doesn’t feel great, users can see the file is there but don't know they can't access it. We might want to (a) reduce the retry times, and/or (b) mark files as ‘not transferred yet’, i.e. by whether or not they have a checksum

**Comment by jackleland** [comment]
@nmassey001

**Comment by nmassey001** [comment]
I think this is fine and as by the design.
