### ISSUE TITLE
Add autogenerate config file

### ISSUE THREAD

**Issue by nmassey001** [cedadev/nlds#78]
This could go in the nlds client repo issues as well.

We need a way of autogenerating the ~/.nlds-config file for users.
This requires the keys and scopes for the nlds-api as well as the keys for the object storage tenancy.

**Comment by jackleland** [comment]
Keys for the object storage tenancy can now be obtained successfully from the objectstore portal if the appropriate jasmin service has been granted

**Comment by jackleland** [comment]
Addressed as of d01a891719e0b0415d3d5cff407cd7c02c387ec7
